[package]
name = "minimize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc_smir = { path = "./project-stable-mir" }
gen-minirust = { path = "../gen-minirust" }
